os/board/image-matrix.groovy, os/board/packages-matrix.groovy, os/board/vm-matrix.groovy, os/kola/qemu.groovy, os/manifest.groovy, os/sdk.groovy, os/toolchains.groovy
The first patch, ```Specify sdk as node constraint```, is the only one we really need, which allows for arm64 nodes.  It will require you to add a label 'sdk' to your jenkins nodes.
The other patches are just minor feature improvements.
=> general enhancements

os/board/vm-matrix.groovy
Depends on https://github.com/coreos/coreos-overlay/pull/2482.
cc @vielmetti
=> vm-matrix: Enable arm64 packet build

os/docs-sync.groovy, vars/createPullRequest.groovy, vars/createPullRequest.txt
This should make pull requests work after the latest @coreosbot catastrophe.  It also adds a stage that automates cleanup of old releases.
=> Some fixes for the docs sync job

os/kola/gce.groovy
=> os/kola/gce: ore create-image moved to a subcommand

os/kola/aws.groovy
kola will read the region from `AWS_REGION`, but that's confusing when rerunning a test by manually copying the kola command line from the log.
=> os/kola/aws: Pass --aws-region to "kola run"

os/manifest.groovy
You can now give `master` as the `RELEASE_BASE` parameter to use binary packages from the last successful master build (probably a nightly).  It defines success as all kola tests passing on the base amd64 image.
=> Support easier scratch builds off master

os/kola/aws.groovy, os/kola/gce.groovy
This matches the qemu timeout. In practice, aws runs seem to be brushing
against the timeout. GCE runs don't, but I think it's reasonable to keep
it consistent with the other timeouts.
=> kola/{aws,gce}: increase timeout

os/kola/aws.groovy
`m1.small` produces a bunch of intermittent problems we're not going to debug right now.
=> kola/aws: Test PV instances on m3.medium

os/board/image-matrix.groovy, os/board/packages-matrix.groovy, os/board/vm-matrix.groovy, os/docs-sync.groovy, os/manifest.groovy, os/sdk.groovy, os/toolchains.groovy
This allows branching the scripts' execution at build time along with the options that branch supports.  It also allows branching the list of image formats produced during a release.
=> Read OS build scripts from the scripts repository

os/board/vm-matrix.groovy, os/docs-sync.groovy, os/kola/packet.groovy
I'm just pushing this now in preparation for coreos-inc/coreos-pages#1717.
=> os/docs-sync: Use new docs data for pruning releases

os/kola/gce.groovy, os/kola/packet.groovy
Make it easier to distinguish Jenkins-spawned instances from manual kola runs.
=> os/kola: Set instance basename on GCE and Packet

os/board/vm-matrix.groovy
VMDK images are currently failing to import.
https://github.com/coreos/bugs/issues/2107
https://github.com/coreos/mantle/pull/678
=> os/board/vm-matrix: Switch plume pre-release to raw AMI image

os/board/vm-matrix.groovy
VMDKs appear to work again.
This reverts commit 0e0643120e7e75feaf6d493e346569f20b6faa4c.
=> Revert "os/board/vm-matrix: Switch plume pre-release to raw AMI image"

os/board/image-matrix.groovy, os/board/packages-matrix.groovy, os/manifest.groovy, os/toolchains.groovy, resources/com/coreos/profiles/alpha.json, resources/com/coreos/profiles/beta.json, resources/com/coreos/profiles/developer.json, resources/com/coreos/profiles/embargoed-alpha.json, resources/com/coreos/profiles/embargoed-beta.json, resources/com/coreos/profiles/embargoed-stable.json, resources/com/coreos/profiles/embargoed.json, resources/com/coreos/profiles/stable.json
This adds the necessary variables for uploading and downloading torcx
packages at various points, as well as for setting the download root
users will be able to access packages at.
i've attempted to include correct configurations for nightlies and all
channels.
This change should have no effect until https://github.com/coreos/scripts/pull/737 is merged
=> *: add torcx download root

resources/com/coreos/profiles/embargoed.json
We moved the hardcoded ip and paths around a little bit.
Notably, the naming more closely matches our github naming, which makes
repo happier.
=> profiles: update static ip

os/board/image-matrix.groovy, os/kola/dev-container.groovy
This runs through the documented steps to prepare for building new kernel modules.  It actually tests a few different parts, like binary package downloads, functioning build tools, valid overlay repositories, etc.
The test will not fail the entire build, since there are a known limitations, like binary packages will not be public at the time for embargoed builds.
Note the job is under the "kola" directory since that is where all other tests are stored, but this does not run kola.
=> os/kola/dev-container: Test the developer container

os/kola/gce.groovy
The image is easy to recreate from the uploaded tarball if we later need it for manual testing.
=> os/kola/gce: delete GCE image when done with it

os/kola/dev-container.groovy
The original commands were taken from the documentation, which expects to build modules for the host kernel.  The host kernel will not always match the version being built and tested here, though, so this takes the config from the binary package that was just built.  That package has to be downloaded and extracted in tmpfs to avoid filling the disk image.
=> os/kola/dev-container: Use the kernel config that was just built

os/kola/oci.groovy
Currently there is a bug where if the previous build produced a
test.tap and the next build fails inside of eitherthe GPG setup or
the cork update the build will output the previous runs test.tap
This moves the `rm` of `*.tap` & `_kola_temp*` earlier in the build
process to remove this.
=> os/kola/oci: move rm of *.tap earlier

os/tectonic-nightly.groovy
The `tectonic-smoke-test-env` container has to be bumped as a result of a refactor of the aws.iam module in the tectonic-installer repo. Also bumps the `tectonic_builder` image to match current master and adds a slack notification (currently sending a DM instead of posting to the default channel) on failure.
=> Bump tectonic nightly containers

os/tectonic-nightly.groovy
Currently it's using the wrong color & the message is in single quotes
causing the `$BUILD_URL` variable to not expand.
=> os/tectonic-nightly: fix slack message

os/gc.groovy
Adds a job to run the ore gc command on all platforms.
Depends on: https://github.com/coreos/mantle/pull/783
=> os: add gc job

os/kola/aws.groovy, os/kola/do.groovy, os/kola/gce.groovy, os/kola/oci.groovy, os/kola/packet.groovy, os/kola/qemu.groovy, os/kola/qemu_uefi.groovy
If any tests fail in a kola run posts a slack message with a list of
failed tests. Parses the list of failed test from the json output via
jq.
=> os/kola: send summary of failures to slack

os/kola/aws.groovy
Only the first 100 `t2` instances per region per account per day receive launch CPU credits. Now that AWS has per-second instance billing and we have automatic instance GC, it's safe to switch to a type without this limitation.
=> os/kola/aws: switch HVM instance type to m4.large

os/release_oci.groovy
Adds a seperate release job specifically for OCI. This is a temporary
workaround until the new OCI SDK launches and we're able to build out
the plume command for the OCI platform.
Currently only the alpha channel will be released.
=> os: add OCI release job

os/kola/oci.groovy
Currently the `oci` command-line tool spits out WARNING messages telling
the user to run a setup command to repair the file permissions. This
ends up amounting to changing the file mode of the config & RSA private
key to 0600. This PR pre-emptively changes the file mode as soon as they
are moved from the dynamic location created via credentials.
=> os/kola/oci: fix file permissions

os/kola/oci.groovy
Currently we don't assert that the image is available after the 1 hour
loop before running kola.
=> os/kola/oci: exit if image not available after 1 hour

os/board/image-matrix.groovy, os/board/packages-matrix.groovy, os/board/sign-image.groovy, os/board/vm-matrix.groovy, os/kola/do.groovy, os/kola/oci.groovy, os/kola/packet.groovy, os/kola/qemu.groovy, os/kola/qemu_uefi.groovy, os/manifest.groovy, os/mirror/nightly.groovy, os/release_oci.groovy, os/sdk.groovy, os/toolchains.groovy
Our jenkins jobs will re-use an existing set of git repoitories on the
node, and depending on what job ran previously, 'repo sync' may need
the --force-sync flag to get the repoitories into the correct state.
Fixes errors like these:
error: Cannot fetch coreos/coreos-overlay GitError: --force-sync not enabled; cannot overwrite a local work tree.
=> Add --force-sync to cork update

os/kola/dev-container.groovy
The emerge-gitclone command expects to work with release numbers to determine where to find the kernel.  When building off master, the major version number is the same as the latest alpha.
To work around this, test if the version string contains a "master" substring, and check out the master branches' ebuilds if so.
=> os/kola/dev-container: Use the master branch's kernel correctly

os/kola/qemu_uefi.groovy
The arm tests for qemu_uefi always time out. Bump the timeout so they
(hopefully) do not.
=> os/kola/qemu_uefi: bump timeout to 120m

os/board/sign-image.groovy, os/docs-sync.groovy, os/kola/do.groovy, os/kola/oci.groovy, os/kola/packet.groovy, os/kola/qemu.groovy, os/kola/qemu_uefi.groovy, os/manifest.groovy, os/mirror/nightly.groovy, os/release_oci.groovy
As of coreos/mantle#814 cork now defaults to experimental and the flag
itself is deprecated. Drops the flag to remove warnings.
=> os/*: drop experimental flag from cork

os/kola/aws.groovy, os/kola/do.groovy, os/kola/gce.groovy, os/kola/packet.groovy, os/kola/qemu.groovy, os/kola/qemu_uefi.groovy
GCE is always timing out, and the others are usually within 15 minutes of the limit.
=> os/kola: Bump most timeouts to account for more tests

os/kola/dev-container.groovy
Allow multiple dev-container jobs to run simultaneously on a worker.  Fixes error:
Failed to register machine: Machine 'coreos_developer_container.bin' already exists
=> os/kola/dev-container: Uniquely name each nspawn machine

os/kola/qemu.groovy, os/kola/qemu_uefi.groovy
kola now modifies qemu images automatically; `kola mkimage` was removed.  `qemu_uefi` intentionally tests a vanilla image, so pass `--qemu-skip-mangle` to continue doing so.
Part of https://github.com/coreos/mantle/pull/940.
=> kola/qemu: drop mkimage

resources/com/coreos/profiles/developer.json, resources/com/coreos/profiles/embargoed.json
We're switching to a new Jenkins instance, so bump this value to avoid conflicting tag names.
=> resources: Update the build ID prefix

plugins/cldsv/build.gradle
Current Gradle failed to build with the previous version last time I compiled this plugin, so update it here in case anyone else tries to build this.
=> plugins/cldsv: Bump the Gradle JPI plugin version

os/kola/qemu.groovy, os/manifest.groovy
Fix reusing workspaces while testing pull requests after coreos/go-semver@776a93a64459f9f09ab33d9ef256dd089d70a31c.
=> os/manifest: Drop the + in build metadata

os/update-linux.groovy
This is a far simplified version of what was used previously that only pays attention to 4.19 and master.  It works with the default sandbox restrictions, so it can live in Git now.
=> os/update-linux: Add script for 4.19 kernel updates on master

os/kola/packet.groovy
Per a request from the Packet support team temporarily lower the
parallelization and switch to the c1.small instance type.
=> os/kola/packet: switch to c1.small instances & lower parallel

os/kola/qemu.groovy, os/kola/qemu_uefi.groovy
Updates the glob match pattern used to copy mantle binaries in the QEMU
scripts to skip the s390x directory as it's not used on Container Linux.
=> os/kola/qemu: update glob match pattern in qemu scripts

os/update-linux.groovy
2247 promoted to beta, so we can resume testing beta kernel bumps.
This reverts commit d3d0d9fc3de75da5c47537ed297ea5bbaa8c3c5e.
=> Revert "os/update-linux: don't test beta branch for now"

os/docs-sync.groovy
During the release of 2275.0.0 & 2247.3.0 the 2247.3.0 docs-sync build
was ran without specifying a BASE_VERSION which caused the index.html to
not be generated. Now enforce that BASE_VERSION is specified for any
builds on channels other than alpha or alpha builds that are not a X.0.Z
version.
=> os/docs-sync: disallow BASE_VERSION empty for non-alpha X.0.Z builds

init.groovy
The mantle project has created a branch for CL specifically no longer
guaranteeing that the master branch will build successfully on CL.
=> init.groovy: switch to cl branch for master-builder mantle job

os/sdk.groovy, os/toolchains.groovy
Take 2: using `GIT_CONFIG` doesn't work because `cork` filters it out:
https://github.com/coreos/mantle/blob/6e1ae57e83bf7835a0c20986d41edf7fb52aa4b3/sdk/create.go#L67-L75
Instead use `GIT_{AUTHOR,COMMITTER}_{NAME,EMAIL}` which should pass
through.
=> os/{sdk,toolchains}: set git config user.{user,name} via env vars

os/kola/qemu_uefi.groovy
Missed this one in the previous commit.
=> os/kola/qemu_uefi: also inject GIT_* env vars

os/docs-sync.groovy
Should make it easier to find out what's going on if one messes up the
parameters.
(Would be cool if Jenkins/Groovy had the equivalent of `set -x` too).
=> docs-groovy: improve error mode when checking base upfront
